### ISSUE TITLE
Update target values for example forecast hub data

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubExamples#10]
This will be done after changes are made in the example-complex-forecast-hub repository with the source data, see https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/issues/25.

**Comment by bsweger** [comment]
Related PR from complex-example-hub: https://github.com/Infectious-Disease-Modeling-Hubs/hubExamples/issues/10

Will work on this issue once the above is reviewed and merged.

**Comment by elray1** [comment]
When we do this, let's rename the data object to `target_observations`
