### ISSUE TITLE
Model output Example Class

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubExamples#17]
The forecast and scenario output examples are not of the same class. `scenario_outputs` is also a `"model_out_tbl"`. Should we harmonize the class of these two object? (if so, I will tend to add the `"model_out_tbl"` class to the forecast example)

``` r
class(hubExamples::scenario_outputs)
#> [1] "model_out_tbl" "tbl_df"        "tbl"           "data.frame"
class(hubExamples::forecast_outputs)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2024-04-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by elray1** [comment]
this makes sense to me.
